pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - 'status-success=ci/circleci'
      - 'status-success=DCO'
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: smart
