pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - status-success=ci/circleci
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
