# VUTTR API

Uma API para a aplicação VUTTR (Very Useful Tools to Remember), para gerenciar ferramentas,
onde um usuário logado pode listar/criar/editar/excluir ferramentas.

# Group Ferramentas


## Ferramentas [/tools]
Endpoint para criar/editar/apagar/listar/filtrar ferramentas


### Listar todas ferramentas cadastradas [GET /api/v1/tools]


+ Request returns tool collections
**GET**&nbsp;&nbsp;`/api/v1/tools`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

+ Response 200

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            [
              {
                "id": 6022,
                "title": "et",
                "link": "http://corwin.co/yelena",
                "description": "Vel repudiandae eum. Voluptatibus unde cumque. Ratione ullam accusamus. Eaque non ut. Consectetur a.",
                "tags": [
                  "webapps",
                  "organization",
                  "domain",
                  "writing",
                  "collaboration"
                ],
                "created_by": "589"
              },
              {
                "id": 6023,
                "title": "rerum",
                "link": "http://kozeyjacobson.co/aurelia_moore",
                "description": "Eaque explicabo velit. Velit voluptate quia. Sed quia reprehenderit. Enim sit mollitia. Error sint .",
                "tags": [
                  "webapps",
                  "calendar",
                  "https",
                  "planning",
                  "collaboration"
                ],
                "created_by": "589"
              },
              {
                "id": 6024,
                "title": "voluptatem",
                "link": "http://ratke.io/bea",
                "description": "Iure qui maiores. Aut error dicta. Nisi magni quos. Magni quae non. Minima occaecati saepe. Porro v.",
                "tags": [
                  "developer",
                  "calendar",
                  "proxy",
                  "writing",
                  "https"
                ],
                "created_by": "589"
              },
              {
                "id": 6025,
                "title": "laborum",
                "link": "http://mannmohr.biz/teddy",
                "description": "Nobis ea ullam. Enim est tempora. Qui exercitationem eaque. Voluptates accusamus consequatur. Asper.",
                "tags": [
                  "organizing",
                  "domain",
                  "calendar",
                  "webapps",
                  "collaboration"
                ],
                "created_by": "589"
              },
              {
                "id": 6026,
                "title": "blanditiis",
                "link": "http://rodriguezkiehn.io/leonard",
                "description": "Quis qui laborum. Adipisci enim excepturi. Dolorem delectus ex. Illo excepturi expedita. Sit et nes.",
                "tags": [
                  "calendar",
                  "proxy",
                  "node",
                  "developer",
                  "planning"
                ],
                "created_by": "589"
              },
              {
                "id": 6027,
                "title": "voluptas",
                "link": "http://reinger.io/annis",
                "description": "Libero sit quasi. Rem totam nisi. Delectus nostrum quod. Quas aut aut. Doloremque vel maxime. Non n.",
                "tags": [
                  "organizing",
                  "calendar",
                  "https",
                  "planning",
                  "proxy"
                ],
                "created_by": "589"
              },
              {
                "id": 6028,
                "title": "dolores",
                "link": "http://rodriguezlubowitz.net/jacob",
                "description": "Reprehenderit aliquam voluptas. Doloremque laboriosam qui. Optio dolores sunt. Ipsa odit soluta. Te.",
                "tags": [
                  "developer",
                  "calendar",
                  "collaboration",
                  "writing",
                  "domain"
                ],
                "created_by": "589"
              },
              {
                "id": 6029,
                "title": "sit",
                "link": "http://jacobson.com/gene_ratke",
                "description": "Aliquam voluptatum aut. Sed sed dolorem. Et iusto et. Reiciendis maiores nisi. In eos voluptatem. Q.",
                "tags": [
                  "proxy",
                  "node",
                  "planning",
                  "organizing",
                  "developer"
                ],
                "created_by": "589"
              },
              {
                "id": 6030,
                "title": "nam",
                "link": "http://haleycole.info/sung",
                "description": "Magni velit sed. Cum laboriosam tempore. Velit aut porro. Minima voluptates quod. Mollitia et non. .",
                "tags": [
                  "organization",
                  "proxy",
                  "webapps",
                  "collaboration",
                  "organizing"
                ],
                "created_by": "589"
              },
              {
                "id": 6031,
                "title": "suscipit",
                "link": "http://halvorsonmertz.info/dionna",
                "description": "Molestiae qui tempora. Vel aut ut. Eos voluptatem ullam. Fugit perferendis quia. Omnis magni et. Be.",
                "tags": [
                  "writing",
                  "proxy",
                  "planning",
                  "domain",
                  "calendar"
                ],
                "created_by": "589"
              }
            ]

### Listar uma ferramenta por ID [GET /tools/{id}]

+ Parameters
    + id: `10` (number, required) - Id da ferramenta

+ Request returns a tool collection
**GET**&nbsp;&nbsp;`/api/v1/tools/6032`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

+ Response 200

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "id": 6032,
              "title": "voluptate",
              "link": "http://kulascollins.biz/cinda",
              "description": "Est ullam soluta. Expedita cupiditate odit. Occaecati eos omnis. Et sapiente qui. Molestiae et numq.",
              "tags": [
                "calendar",
                "webapps",
                "organization",
                "planning",
                "proxy"
              ],
              "created_by": "590"
            }

+ Request return a not found message
**GET**&nbsp;&nbsp;`/api/v1/tools/120`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

+ Response 404

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "message": "Couldn't find Tool with 'id'=120"
            }

### Filtrar ferramentas utilizando uma busca por tag [GET /tools/?tag={tag}]

+ Parameters
    + tags: `node` (string, required) - Tag a ser filtrada

+ Request returns tools tagged with this tag
**GET**&nbsp;&nbsp;`/api/v1/tools?tag=node`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

+ Response 200

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            [
              {
                "id": 6053,
                "title": "aperiam",
                "link": "http://trantowwintheiser.info/timmy.ankunding",
                "description": "Dolorem cumque ullam. Pariatur recusandae numquam. Rerum aut ut. Sint perspiciatis consequatur. Ver.",
                "tags": [
                  "developer",
                  "node",
                  "calendar",
                  "organizing",
                  "webapps"
                ],
                "created_by": "592"
              },
              {
                "id": 6057,
                "title": "explicabo",
                "link": "http://kihnruecker.net/ila.ziemann",
                "description": "Nostrum quod ducimus. Consequatur ipsum dolores. Ab beatae accusamus. Dolore earum perferendis. Mol.",
                "tags": [
                  "collaboration",
                  "calendar",
                  "proxy",
                  "node",
                  "writing"
                ],
                "created_by": "592"
              }
            ]

+ Request body response is empty
**GET**&nbsp;&nbsp;`/api/v1/tools?tag=bla`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

+ Response 404

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body



### Cadastrar uma nova ferramenta [POST /tools]

+ Parameters
    + title: `quod` (string, required) - Nome da ferramenta
    + link: `http%3A%2F%2Fsauer.name%2Fangela` (string, required) - Link da ferramenta
    + description: `Modi+sit+consequatur` (string, required) - Descrição da ferramenta
    + tags: `%5B%22node%22%2C+%22web%22%5D` (array, required) - Tags da ferramenta

+ Request creates a new tool collection
**POST**&nbsp;&nbsp;`/api/v1/tools`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

    + Body

            {
              "title": "notebook",
              "link": "https://example.com",
              "description": "Local app manager. Start apps within your browser, developer tool with local\n                        .localhost domain and https out of the box.",
              "tags": [
                "electronic",
                "organizing",
                "computer",
                "developer",
                "node"
              ],
              "created_by": "594"
            }

+ Response 201

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "id": 6082,
              "title": "notebook",
              "link": "https://example.com",
              "description": "Local app manager. Start apps within your browser, developer tool with local\n                        .localhost domain and https out of the box.",
              "tags": [
                "electronic",
                "organizing",
                "computer",
                "developer",
                "node"
              ],
              "created_by": "594"
            }

+ Request returns a validation failure message
**POST**&nbsp;&nbsp;`/api/v1/tools`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

    + Body

            {
              "title": "notebook",
              "created_by": "595"
            }

+ Response 422

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "message": "Validation failed: Link can't be blank, Description can't be blank, Tags can't be blank"
            }

### Editar uma ferramenta [PUT /tools/{id}]

+ Parameters
    + title: `quod` (string, required) - Nome da ferramenta
    + link: `http%3A%2F%2Fsauer.name%2Fangela` (string, required) - Link da ferramenta
    + description: `Modi+sit+consequatur` (string, required) - Descrição da ferramenta
    + tags: `%5B%22node%22%2C+%22web%22%5D` (array, required) - Tags da ferramenta

+ Request updates the requested tool collection
**PUT**&nbsp;&nbsp;`/api/v1/tools/6093`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

    + Body

            {
              "title": "Lorem"
            }

+ Response 204

+ Request return a not found message
**PUT**&nbsp;&nbsp;`/api/v1/tools/120`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

    + Body

            "{\"title\":\"Lorem\"}"

+ Response 404

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "message": "Couldn't find Tool with 'id'=120"
            }

### Apagar uma ferramenta por ID [DELETE /tools/{id}]

+ Parameters
    + id: `10` (number, required) - Id da ferramenta

+ Request deletes the requested tool collection
**DELETE**&nbsp;&nbsp;`/api/v1/tools/6113`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

+ Response 404

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "message": "Couldn't find Tool with 'id'=6113"
            }

+ Request return a not found message
**DELETE**&nbsp;&nbsp;`/api/v1/tools/120`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

+ Response 404

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "message": "Couldn't find Tool with 'id'=120"
            }

# Group Usuários


## Usuários [/signup]
Endpoint para cadastrar um novo usuário


### Cadastrar um novo usuário [POST /signup]

+ Parameters
    + name: `Maria+Joana` (string, required) - Nome do usuário
    + email: `mariajoana%40hotmail.com` (string, required) - Email do usuário
    + password: `cec7052fcd3` (string, required) - Senha do usuário
    + password_confirmation: `cec7052fcd3` (string, required) - Confirmação da senha do usuário

+ Request creates a new user
**POST**&nbsp;&nbsp;`/api/v1/signup`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

    + Body

            {
              "name": "bennie",
              "email": "bennie@zboncaknienow.io",
              "password": "C61k7w84P",
              "password_confirmation": "C61k7w84P"
            }

+ Response 201

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "message": "Account created successfully",
              "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2MDAsImV4cGlyYXRpb24iOjE1NTg3MjExMTF9.7u4ak1nnCifkI9TnfxxX4HtdAZoXtsK6JdluMYeeyFg"
            }

+ Request returns an authentication token
**POST**&nbsp;&nbsp;`/api/v1/signup`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

    + Body

            {
              "name": "elin",
              "email": "elin@bernierrobel.name",
              "password": "H1Zw6x2qZs",
              "password_confirmation": "H1Zw6x2qZs"
            }

+ Response 201

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "message": "Account created successfully",
              "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2MDEsImV4cGlyYXRpb24iOjE1NTg3MjExMTF9.aencnoHKoyKU3kSQbN0R81q6EyYH9z1NJCfE9eC5JpI"
            }

+ Request does not create a new user
**POST**&nbsp;&nbsp;`/api/v1/signup`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

+ Response 422

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "message": "Validation failed: Password can't be blank, Name can't be blank, Email can't be blank, Password digest can't be blank"
            }

+ Request returns failure message
**POST**&nbsp;&nbsp;`/api/v1/signup`

    + Headers

            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: application/json

+ Response 422

    + Headers

            Content-Type: application/json; charset=utf-8

    + Body

            {
              "message": "Validation failed: Password can't be blank, Name can't be blank, Email can't be blank, Password digest can't be blank"
            }
